# Generated by Django 5.0.6 on 2026-05-26 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('wattage_w', models.FloatField()),
                ('typical_hours_per_day', models.FloatField(default=0)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'appliance_catalog',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserAppliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wattage_w', models.FloatField()),
                ('hours_per_day', models.FloatField()),
                ('quantity', models.IntegerField(default=1)),
                ('category', models.CharField(default='Custom', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appliances.appliancecatalog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_appliances',
                'ordering': ['-wattage_w'],
            },
        ),
    ]
