# Generated by Django 5.0.6 on 2026-05-26 06:42

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(default='ESP32 Meter', max_length=100)),
                ('token', models.CharField(default=secrets.token_hex, help_text='Bearer token embedded in ESP32 firmware', max_length=64, unique=True)),
                ('firmware_version', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'iot_devices',
            },
        ),
        migrations.CreateModel(
            name='IoTReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True)),
                ('voltage', models.FloatField(help_text='V')),
                ('current', models.FloatField(help_text='A')),
                ('power', models.FloatField(help_text='W — real power')),
                ('energy', models.FloatField(help_text='kWh — cumulative')),
                ('frequency', models.FloatField(default=50.0, help_text='Hz')),
                ('power_factor', models.FloatField(default=1.0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='iot.iotdevice')),
            ],
            options={
                'db_table': 'iot_readings',
                'indexes': [models.Index(fields=['device', 'time'], name='iot_reading_device__7a2d87_idx')],
            },
        ),
    ]
