# Generated by Django 5.0.6 on 2026-05-26 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTSimulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('wattage_w', models.FloatField(default=1500.0, help_text='Current simulated load (W)')),
                ('interval_seconds', models.IntegerField(default=5, help_text='Seconds between readings')),
                ('celery_task_id', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simulator', to='iot.iotdevice')),
            ],
            options={
                'db_table': 'iot_simulators',
            },
        ),
    ]
