# Generated by Django 5.0.6 on 2026-05-26 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_id', models.IntegerField(blank=True, null=True)),
                ('analysis', models.JSONField()),
                ('predicted_units', models.IntegerField()),
                ('predicted_bill_pkr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_pkr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('units_gap', models.IntegerField(default=0)),
                ('pkr_gap', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('within_budget', models.BooleanField(default=False)),
                ('applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance_name', models.CharField(max_length=100)),
                ('hours_reduced', models.FloatField()),
                ('units_saved', models.FloatField()),
                ('pkr_saved', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_total_units', models.IntegerField()),
                ('new_bill_pkr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slab_crossed', models.BooleanField(default=False)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reductions', to='recommendations.recommendation')),
            ],
            options={
                'db_table': 'reduction_plans',
            },
        ),
    ]
