# Generated by Django 5.0.6 on 2026-05-26 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LescoFetchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('celery_task_id', models.CharField(blank=True, max_length=50)),
                ('months_fetched', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('result_summary', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lesco_fetch_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_label', models.CharField(help_text="e.g. 'Aug-25'", max_length=10)),
                ('year', models.IntegerField()),
                ('mon_idx', models.IntegerField(help_text='1–12')),
                ('units', models.IntegerField()),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('source', models.CharField(choices=[('lesco_fetch', 'LESCO Auto-Fetch'), ('ocr', 'OCR Scan'), ('manual', 'Manual Entry')], default='manual', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bill_records',
                'ordering': ['year', 'mon_idx'],
                'unique_together': {('user', 'year', 'mon_idx')},
            },
        ),
    ]
