# Generated by Django 5.0.6 on 2026-06-19 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billrecord',
            options={'ordering': ['-year', '-mon_idx']},
        ),
    ]
