# Generated by Django 5.0.6 on 2026-05-26 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ocr_uploads/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('celery_task_id', models.CharField(blank=True, max_length=50)),
                ('extracted_ref_no', models.CharField(blank=True, max_length=25)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=50)),
                ('variants_run', models.IntegerField(default=0)),
                ('raw_result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ocr_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
