# Generated by Django 5.0.6 on 2026-05-26 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_pkr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_units', models.IntegerField(blank=True, null=True)),
                ('alert_at_75_pct', models.BooleanField(default=True)),
                ('alert_at_100_pct', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'budgets',
            },
        ),
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_pct', models.IntegerField(choices=[(75, '75%'), (100, '100%')])),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_units', models.IntegerField()),
                ('consumed_pkr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='budget.budget')),
            ],
            options={
                'db_table': 'budget_alerts',
                'ordering': ['-triggered_at'],
            },
        ),
    ]
